# ollama_gateway/ollama_deployer/backup.py

#!/usr/bin/env python3
"""
Backup module for Ollama PRO+ Cluster.

Chức năng:
- Yêu cầu quyền root (Linux)
- Tạo thư mục backup
- Sinh cron script daily trong /etc/cron.daily
- Backup incremental theo ngày (backup-YYYY-MM-DD)
- Không ghi đè backup cũ
- Không crash nếu thư mục nguồn không tồn tại
"""

import os
from pathlib import Path


# ============================================================
#  LOGGING
# ============================================================
def log(msg: str) -> None:
    print(f"[BACKUP] {msg}")


# ============================================================
#  ROOT CHECK
# ============================================================
def is_linux_root() -> bool:
    """Trả về True nếu đang chạy Linux và user là root."""
    if hasattr(os, "geteuid"):
        return os.geteuid() == 0
    return False  # Windows


def require_root() -> None:
    """Yêu cầu root trên Linux, Windows thì bỏ qua."""
    if hasattr(os, "geteuid") and not is_linux_root():
        raise SystemExit("Please run as root (sudo).")


# ============================================================
#  PATHS
# ============================================================
BACKUP_DIR = Path("/var/backups/ollama-models")
SOURCE_DIR = Path("/root/.ollama/models")
CRON_FILE = Path("/etc/cron.daily/ollama-backup")


# ============================================================
#  CREATE BACKUP SCRIPT
# ============================================================
def generate_script() -> str:
    """Sinh nội dung script backup (dễ test hơn)."""
    return f"""#!/bin/bash
# Auto-generated by Ollama PRO+ deployer
set -e
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

SRC="{SOURCE_DIR}"
DST="{BACKUP_DIR}"

if [ ! -d "$SRC" ]; then
    echo "[BACKUP] Source directory not found: $SRC"
    exit 0
fi

mkdir -p "$DST"

STAMP=$(date +"%Y-%m-%d")
TARGET="$DST/backup-$STAMP"

if [ -d "$TARGET" ]; then
    echo "[BACKUP] Backup for today already exists: $TARGET"
    exit 0
fi

cp -a "$SRC" "$TARGET"

echo "[BACKUP] Backup completed: $TARGET"
"""


def create_backup_script() -> None:
    """Ghi script backup vào /etc/cron.daily."""
    CRON_FILE.parent.mkdir(parents=True, exist_ok=True)

    script = generate_script()
    CRON_FILE.write_text(script)
    CRON_FILE.chmod(0o700)

    log(f"Cron script installed: {CRON_FILE}")


# ============================================================
#  SETUP BACKUP SYSTEM
# ============================================================
def setup_backup() -> None:
    """Thiết lập hệ thống backup."""
    require_root()

    log("Setting up Ollama model backup system...")

    BACKUP_DIR.mkdir(parents=True, exist_ok=True)

    create_backup_script()

    log("Backup system ready.")


if __name__ == "__main__":
    setup_backup()

